import { readFileSync } from 'node:fs';
import { VFS } from '../src/vfs/VFS.js';
import { MemFS } from '../src/vfs/MemFS.js';
import { EventBus } from '../src/core/EventBus.js';
import { WasmRuntime } from '../src/wasm/WasmRuntime.js';

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('  ok  ', m); } else { fail++; console.log('  FAIL', m); } };
const dec = (b) => new TextDecoder().decode(b);

// build a VFS with a /bin (wasm) and /home/project (source) layout
const bus = new EventBus();
const vfs = new VFS();
await vfs.mount('/', new MemFS());
await vfs.mkdir('/bin');
await vfs.writeFile('/bin/hello.wasm', readFileSync(new URL('./fixtures/hello.wasm', import.meta.url)));
await vfs.writeFile('/bin/cat.wasm', readFileSync(new URL('./fixtures/cat.wasm', import.meta.url)));
await vfs.writeFile('/bin/writer.wasm', readFileSync(new URL('./fixtures/writer.wasm', import.meta.url)));
await vfs.mkdir('/home/project');
await vfs.writeText('/home/project/input.txt', 'source line A\nsource line B\n');

const events = [];
bus.on('*', (d, t) => { if (String(t).startsWith('wasm:')) events.push(t); });
const rt = new WasmRuntime({ vfs, bus });

// 1) load + run hello, capture stdout
{
  const mod = await rt.load('/bin/hello.wasm');
  ok(mod.isWasi, 'hello detected as WASI module');
  ok(mod.exports.some(e => e.name === '_start'), 'hello exports _start');
  const r = await rt.run(mod, {});
  ok(r.exitCode === 0, 'hello exit 0');
  ok(r.stdoutText === 'hello from wasi\n', 'hello stdout captured: ' + JSON.stringify(r.stdoutText));
}

// 2) run cat by PATH (not handle), reading a VFS file via preopen
{
  let live = '';
  const r = await rt.run('/bin/cat.wasm', {
    preopens: { '.': '/home/project' },       // guest "." -> VFS /home/project
    stdout: (b) => { live += dec(b); },
  });
  ok(r.exitCode === 0, 'cat exit 0');
  ok(r.stdoutText === 'source line A\nsource line B\n', 'cat read VFS file through preopen');
  ok(live === r.stdoutText, 'live stdout sink matches buffered');
}

// 3) writer creates out.txt in the preopen -> must appear in the VFS (writeback)
{
  const r = await rt.run('/bin/writer.wasm', { preopens: { '.': '/home/project' } });
  ok(r.exitCode === 0, 'writer exit 0');
  const exists = await vfs.exists('/home/project/out.txt');
  ok(exists, 'writeback created /home/project/out.txt in VFS');
  const txt = await vfs.readText('/home/project/out.txt');
  ok(txt === 'generated by wasm\n', 'writeback content correct: ' + JSON.stringify(txt));
}

// 4) compile cache: second load of same bytes must hit cache (no recompile)
{
  events.length = 0;
  await rt.load('/bin/hello.wasm');
  const compileEvents = events.filter(t => t === 'wasm:compile');
  ok(compileEvents.length === 1, 'second load emitted one compile event');
}

// 5) readonly run (writeback:false) must NOT persist
{
  await vfs.remove('/home/project/out.txt');
  const r = await rt.run('/bin/writer.wasm', { preopens: { '.': '/home/project' }, writeback: false });
  ok(r.exitCode === 0, 'writer (no writeback) exit 0');
  const exists = await vfs.exists('/home/project/out.txt');
  ok(!exists, 'writeback:false left VFS untouched');
}

console.log(`\nWASM RUNTIME: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
