import wabtInit from 'wabt';
import { writeFileSync } from 'node:fs';

const wabt = await wabtInit();

function compile(name, wat) {
  const m = wabt.parseWat(name, wat, { simd: true, bulk_memory: true });
  const { buffer } = m.toBinary({});
  writeFileSync(new URL(`./${name}.wasm`, import.meta.url), Buffer.from(buffer));
  console.log(`built ${name}.wasm (${buffer.length} bytes)`);
  m.destroy();
}

// 1) hello -> stdout via fd_write
compile('hello', `
(module
  (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (memory (export "memory") 1)
  (data (i32.const 64) "hello from wasi\\0a")
  (func (export "_start")
    (i32.store (i32.const 0) (i32.const 64))   ;; iov.base
    (i32.store (i32.const 4) (i32.const 16))   ;; iov.len
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 32)))
    (call $proc_exit (i32.const 0))
  )
)`);

// 2) cat: discover preopen fd=3, open "input.txt", read, echo to stdout
compile('cat', `
(module
  (import "wasi_snapshot_preview1" "fd_prestat_get"
    (func $prestat_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "path_open"
    (func $path_open (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_read"
    (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (memory (export "memory") 2)
  (data (i32.const 16) "input.txt")        ;; len 9
  (func (export "_start") (local $fd i32) (local $n i32)
    ;; verify preopen fd=3 exists
    (if (i32.ne (call $prestat_get (i32.const 3) (i32.const 0)) (i32.const 0))
      (then (call $proc_exit (i32.const 10))))
    ;; path_open(dirfd=3, dirflags=1(symlink_follow), path=16, path_len=9,
    ;;   oflags=0, rights_base=all, rights_inh=all, fdflags=0, opened_fd=32)
    (if (i32.ne
          (call $path_open (i32.const 3) (i32.const 1) (i32.const 16) (i32.const 9)
             (i32.const 0) (i64.const -1) (i64.const -1) (i32.const 0) (i32.const 32))
          (i32.const 0))
      (then (call $proc_exit (i32.const 11))))
    (local.set $fd (i32.load (i32.const 32)))
    ;; read iovec @64: base=512 len=1024
    (i32.store (i32.const 64) (i32.const 512))
    (i32.store (i32.const 68) (i32.const 1024))
    (if (i32.ne (call $fd_read (local.get $fd) (i32.const 64) (i32.const 1) (i32.const 40)) (i32.const 0))
      (then (call $proc_exit (i32.const 12))))
    (local.set $n (i32.load (i32.const 40)))
    ;; write iovec @72: base=512 len=n
    (i32.store (i32.const 72) (i32.const 512))
    (i32.store (i32.const 76) (local.get $n))
    (drop (call $fd_write (i32.const 1) (i32.const 72) (i32.const 1) (i32.const 44)))
    (call $proc_exit (i32.const 0))
  )
)`);

// 3) writer: create "out.txt" in preopen 3 and write to it (tests CREAT + writeback)
compile('writer', `
(module
  (import "wasi_snapshot_preview1" "path_open"
    (func $path_open (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_close" (func $fd_close (param i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
  (memory (export "memory") 1)
  (data (i32.const 16) "out.txt")              ;; len 7
  (data (i32.const 64) "generated by wasm\\0a") ;; len 18
  (func (export "_start") (local $fd i32)
    ;; path_open(dirfd=3, dirflags=0, path=16, len=7, oflags=CREAT(1)|TRUNC(8)=9,
    ;;   rights=all, rights_inh=all, fdflags=0, opened=32)
    (if (i32.ne
          (call $path_open (i32.const 3) (i32.const 0) (i32.const 16) (i32.const 7)
             (i32.const 9) (i64.const -1) (i64.const -1) (i32.const 0) (i32.const 32))
          (i32.const 0))
      (then (call $proc_exit (i32.const 20))))
    (local.set $fd (i32.load (i32.const 32)))
    ;; write iovec @40: base=64 len=18
    (i32.store (i32.const 40) (i32.const 64))
    (i32.store (i32.const 44) (i32.const 18))
    (drop (call $fd_write (local.get $fd) (i32.const 40) (i32.const 1) (i32.const 48)))
    (drop (call $fd_close (local.get $fd)))
    (call $proc_exit (i32.const 0))
  )
)`);
